import AppKit

/// Supplies `NSPasteboard.general`'s plain text as optional completion context.
/// No OS copy-timestamp exists, so freshness is stamped when a clipboard change
/// is first observed. Concealed/transient/auto-generated clipboards (set by
/// password managers) are never returned. Main-actor use only.
@MainActor
final class ClipboardContextProvider {
    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int
    private var lastChangedAt: Date?

    /// Pasteboard markers that mean "do not capture".
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        // Launch baseline: a clipboard copied before Inkling launched has no
        // observed change moment, so it stays stale until the user copies again.
        self.lastChangeCount = pasteboard.changeCount
    }

    /// The clipboard's plain text when it changed within `window` seconds and is
    /// not concealed; nil otherwise.
    func freshText(window: TimeInterval, now: Date) -> String? {
        let count = pasteboard.changeCount
        if count != lastChangeCount {
            lastChangeCount = count
            lastChangedAt = now
        }
        guard let changedAt = lastChangedAt, now.timeIntervalSince(changedAt) <= window else { return nil }
        if let types = pasteboard.types,
           types.contains(where: { Self.concealedTypes.contains($0.rawValue) }) {
            return nil
        }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return text
    }
}
